### ISSUE TITLE
App got crash when starting with zero charges

### ISSUE THREAD

**Issue by Back1ng** [Bednyakov/NotPixelMiner#1]
```
Виртуальное окружение уже существует.
Активируем виртуальное окружение...
./run.sh: line 17: .venv/bin/activate: No such file or directory
Установка зависимостей...
Requirement already satisfied: certifi==2024.8.30 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2024.8.30)
Requirement already satisfied: charset-normalizer==3.4.0 in /usr/local/lib64/python3.12/site-packages (from -r requirements.txt (line 2)) (3.4.0)
Requirement already satisfied: idna==3.10 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.10)
Requirement already satisfied: pyaes==1.6.1 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (1.6.1)
Requirement already satisfied: pyasn1==0.6.1 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (0.6.1)
Requirement already satisfied: python-dotenv==1.0.1 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (2.32.3)
Requirement already satisfied: rsa==4.9 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (4.9)
Requirement already satisfied: Telethon==1.37.0 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (1.37.0)
Requirement already satisfied: urllib3==2.2.3 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (2.2.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Запуск main.py...
2024-10-14 11:43:10,053 - NotPixel_logger - INFO - Balance: 13
2024-10-14 11:43:10,055 - NotPixel_logger - INFO - Coins: 0.00026599999999999996
2024-10-14 11:43:10,056 - NotPixel_logger - INFO - Charges: 0
Traceback (most recent call last):
  File "/root/NotPixelMiner/main.py", line 5, in <module>
    main()
  File "/root/NotPixelMiner/app/__init__.py", line 34, in main
    logger.info(f"Balance: {data['balance']}")
                            ^^^^
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value
Завершение работы. Деактивируем виртуальное окружение.
./run.sh: line 37: deactivate: command not found
```

Также подобная ошибка появляется и в процессе использования:
```
Виртуальное окружение уже существует.
Активируем виртуальное окружение...
./run.sh: line 17: .venv/bin/activate: No such file or directory
Установка зависимостей...
Requirement already satisfied: certifi==2024.8.30 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2024.8.30)
Requirement already satisfied: charset-normalizer==3.4.0 in /usr/local/lib64/python3.12/site-packages (from -r requirements.txt (line 2)) (3.4.0)
Requirement already satisfied: idna==3.10 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (3.10)
Requirement already satisfied: pyaes==1.6.1 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (1.6.1)
Requirement already satisfied: pyasn1==0.6.1 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 5)) (0.6.1)
Requirement already satisfied: python-dotenv==1.0.1 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 6)) (1.0.1)
Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 7)) (2.32.3)
Requirement already satisfied: rsa==4.9 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 8)) (4.9)
Requirement already satisfied: Telethon==1.37.0 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 9)) (1.37.0)
Requirement already satisfied: urllib3==2.2.3 in /usr/local/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (2.2.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Запуск main.py...
2024-10-14 12:58:49,720 - NotPixel_logger - INFO - Balance: 164.07455583333666
2024-10-14 12:58:49,722 - NotPixel_logger - INFO - Coins: 0.008328833333333334
2024-10-14 12:58:49,723 - NotPixel_logger - INFO - Charges: 1
2024-10-14 12:58:51,645 - NotPixel_logger - INFO - {'pixelId': 795019, 'newColor': '#7EED56'}
2024-10-14 12:58:57,648 - NotPixel_logger - INFO - Balance: 165.07455583334
2024-10-14 12:58:57,649 - NotPixel_logger - INFO - Копим пиксели...
2024-10-14 13:11:43,976 - NotPixel_logger - INFO - Balance: 165.07455583333666
2024-10-14 13:11:43,977 - NotPixel_logger - INFO - Coins: 0.026092499999999998
2024-10-14 13:11:43,978 - NotPixel_logger - INFO - Charges: 2
2024-10-14 13:11:45,607 - NotPixel_logger - INFO - {'pixelId': 265924, 'newColor': '#E4ABFF'}
2024-10-14 13:11:55,591 - NotPixel_logger - INFO - {'pixelId': 262312, 'newColor': '#FFFFFF'}
2024-10-14 13:11:58,593 - NotPixel_logger - INFO - Balance: 167.07455583334
2024-10-14 13:11:58,595 - NotPixel_logger - INFO - Копим пиксели...
2024-10-14 13:25:38,479 - NotPixel_logger - INFO - Balance: 167.07455583333666
2024-10-14 13:25:38,480 - NotPixel_logger - INFO - Coins: 0.04512083333333333
2024-10-14 13:25:38,481 - NotPixel_logger - INFO - Charges: 1
2024-10-14 13:25:43,707 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:25:48,971 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:25:54,234 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:25:59,465 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:26:04,917 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:26:10,217 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:26:11,828 - NotPixel_logger - INFO - 400 Повторно закрашиваю пиксель...
2024-10-14 13:26:12,659 - NotPixel_logger - INFO - 400 Повторно закрашиваю пиксель...
2024-10-14 13:26:13,089 - NotPixel_logger - INFO - 400 Повторно закрашиваю пиксель...
2024-10-14 13:26:18,306 - NotPixel_logger - INFO - 504 Повторно закрашиваю пиксель...
2024-10-14 13:26:18,307 - NotPixel_logger - ERROR - Ошибка claim: 504
Traceback (most recent call last):
  File "/root/NotPixelMiner/main.py", line 5, in <module>
    main()
  File "/root/NotPixelMiner/app/__init__.py", line 34, in main
    logger.info(f"Balance: {data['balance']}")
```

**Comment by Back1ng** [comment]
I think this now not a problem. Not Pixel now allow painting only on templates, so, bot will not give points.

**Comment by Bednyakov** [comment]
Это поправимо, просто нужно потратить еще немного времени на бот, на днях поправлю механику.
--
Отправлено из  Mail для Android понедельник, 14 октября 2024г., 17:49 +03:00 от Anatoly Elyutin  ***@***.*** :
